### ISSUE TITLE
v3.1.0 claims it has an unused ".eslintrc.yml" rule

### ISSUE THREAD

**Issue by ljharb** [sarbbottam/eslint-find-rules#132]
I updated eslint to v3.1.0 in https://github.com/ljharb/eslint-config and ran `npm run prepublish` (which runs `eslint-find-rules --unused`, among other things).

It complains about two missing rules: "multiline-ternary" which is a new one added in v3.1.0, and ".eslintrc.yml", which is not a rule at all.

**Comment by sarbbottam** [comment]
[eslint-find-rules scans `eslint/lib/rules` directory for all available core rules](https://github.com/sarbbottam/eslint-find-rules/blob/master/src/lib/rule-finder.js#L74)

Looks like a `.eslintrc.yml` was added to `eslint/lib/rules` [three days ago](https://github.com/eslint/eslint/blame/master/lib/rules/.eslintrc.yml), which has created the issue.

Need to filter out any non `.js` file.
