### ISSUE TITLE
Links in output

### ISSUE THREAD

**Issue by jfmengels** [sarbbottam/eslint-find-rules#141]
Atom's [linter-eslint](https://github.com/AtomLinter/linter-eslint) project holds a list of plugin and plugin rules documentation location pair (see https://github.com/AtomLinter/linter-eslint/blob/master/lib/helpers.js#L72-L104). Basically: "For eslint plugin X, the documentation for every rule is in `https://github.com/Gillespie59/eslint-plugin-X/blob/master/docs/' + ruleName + '.md'`.

What do use it for, is at the location where errors are shown, to have a clickable link that opens the browser with the documentation page of that link, which allows you to easily read more about the rule and/or the problem it points out. (in the following screenshot, `no-undef` is clickable)
![image](https://cloud.githubusercontent.com/assets/3869412/17252585/918a431a-55ad-11e6-8264-d6f5ec457b10.png)

A while ago, I thought about moving this project to its own repo (that I discussed in one of the points [here](https://github.com/AtomLinter/linter-eslint/issues/590)), and the creators thought it could be a good idea.

I now thought that this could be pretty useful here. Behind an option, there could be new list formatted like this:

```
accessor-pairs http://eslint.org/docs/rules/accessor-pairs
array-bracket-spacing http://eslint.org/docs/rules/array-bracket-spacing
array-callback-return http://eslint.org/docs/rules/array-callback-return

import/order https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md
```

which would be clickable in the terminal (hopefully in most terminals, otherwise it's copy-pastable, which is still nice), and allow you to quickly find out about a rule.

Right now, I'm wondering whether you'd be interested by this functionality. And if so, I'll be more interested in working on the new repository the plugins (and maybe even integrate it here) :)
What do you think?

FYI: Currently, as that "list" works, every link for an unknown plugin will redirect to a page to help register it.

**Comment by ta2edchimp** [comment]
This is awesome!

If I got it right, you want to make a new module, we could then use as a plugin in `eslint-find-rules`?
That would be really cool and would absolutely help to give the `verbose` output option more value.

**Comment by jfmengels** [comment]
> If I got it right, you want to make a new module, we could then use as a plugin in eslint-find-rules?

You got it right ;)

**Comment by sarbbottam** [comment]
So the documentation links in o/p will be on demand via some options.
Is my comprehension correct?

**Comment by jfmengels** [comment]
Yes, it's too verbose to be there by default.

**Comment by jfmengels** [comment]
I created that new module as I mentionned https://github.com/jfmengels/eslint-rule-documentation/, if you have the time to give me some feedback as to this use-case, that'd be great! I think that what this module is enough to be used here, but just wanted confirmation.

If you don't have the time, no problem, I'll publish in a few days, then see whether it all works out when I try to implement this here ;)

**Comment by sarbbottam** [comment]
looks good 👍

**Comment by ta2edchimp** [comment]
Fantastic! :+1:
