### ISSUE TITLE
Use ES2015?

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-find-rules#154]
Should the codebase be ES2015fied?

@ta2edchimp @ljharb @jfmengels

**Comment by ljharb** [comment]
Since eslint v3 dropped support for < node 4, I think it'd be OK to do so, and update the code accordingly.

Either way, as long as the code is transpiled on prepublish, I don't think it's a big deal either way.

**Comment by sarbbottam** [comment]
Sounds good.

Will create a separate branch and work on ES2015.

**Comment by ta2edchimp** [comment]
Shall we wait postpone correcting the alignment of #146 's output until after the "es2015ification" (what a word)? I guess it would simplify things a lot ...

**Comment by sarbbottam** [comment]
Sure.

**Comment by jfmengels** [comment]
Sounds good to me!
