### ISSUE TITLE
Don't require to specify deprecated rules

### ISSUE THREAD

**Issue by mgol** [sarbbottam/eslint-find-rules#172]
Currently the command `eslint-find-rules -u` ends with an error if you don't specify deprecated rules. Ideally that wouldn't be required; currently I just [put them in a separate section and disable](https://github.com/mgol/eslint-config-mgol/blob/61a129c72391b35a3e2533061855094584d808f5/eslint-config-mgol.js#L258-L261) but that means my config will be broken as soon as those rules are removed which doesn't seem necessary.

I'm not sure if ESLint returns enough data to make it possible; if not we could make it happen upstream first.

**Comment by jfmengels** [comment]
:+1: I like the idea, and ESLint does return enough data to handle that (see [this](https://github.com/eslint/eslint/blob/master/lib/rules/no-native-reassign.js#L22))

From what I can see, it could work for plugin rules too, if we're careful with the format of the rule (ESLint v2 and v3 format), and if they copy the same meta info behavior as ESLint.

The only downside to this, is that you'd need to require all core rules to find out whether they're deprecated, which would make the tool quite a lot slower I'm guessing, but it could be done only if needed, when the right flags are activated (if requiring all those rules is indeed that slow).

**Comment by ta2edchimp** [comment]
👍  making the tool slower is worth it in this case, I guess! At least, when being behind a flag.

**Comment by mgol** [comment]
I've reported an issue upstream that would help for this & similar use cases: https://github.com/eslint/eslint/issues/7021.

**Comment by mateatslc** [comment]
look here for news on this: https://github.com/eslint/eslint/issues/6525

**Comment by randycoulman** [comment]
I looked into doing this at one point and I really love the idea of having this feature.

From my earlier research, I only found one plugin that had deprecated rules ([eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react)), and it doesn't add a `deprecated` flag to the metadata.  Instead, it exports a `deprecatedRules` property alongside its `rules` property.

It might be worth doing a couple of things:

1. Submit a PR to eslint-plugin-react to add the `deprecated` property to its rule metadata.
2. Update the ESLint plugin documentation to recommend doing that in all plugins.

Does anyone know of any other plugins that have deprecated rules?  What do they do?

**Comment by ljharb** [comment]
I would be happy to accept that PR on eslint-plugin-react. eslint-plugin-import has some deprecated rules as well, iirc.

**Comment by randycoulman** [comment]
I'll try to work on a PR on eslint-plugin-react, but it might be a week or so before I can get to it.  If anyone else wants to do it before then, feel free.

eslint-plugin-import just added its first deprecated rule in 2.0, but it's really just a rename of one rule to another, and it doesn't warn about the deprecated name when running it.  I'll look at submitting a PR for that as well at my next opportunity.

**Comment by mvolkmann** [comment]
An example of a rule that is deprecated, but is flagged by eslint-find-rules as being unused is react/no-comment-textnodes.

**Comment by mgol** [comment]
The ESLint PR has landed; I created an issue to switch to the new API: #211. Once that's done, this issue should be easily solvable.

**Comment by alexilyaev** [comment]
@mgol @randycoulman Can we push this forward?
I see there's a PR that requires a review.

Or is there anything else missing?

**Comment by randycoulman** [comment]
We can't do anything here until #237 has been merged.  Once that's done, we'll have to refactor a bit to use the new API to get the full rule definitions (we only use the rule names right now).  Then we can filter out the deprecated rules.

**Comment by ntwb** [comment]
Looking forward to this 😄

**Comment by randycoulman** [comment]
Now that #237 has been merged, this can be started.  I plan to get to it as soon as I can, but I'm a bit busy right now and it might be a week before I get to it.  If someone else wants to run with it, go for it - just let me know so I don't duplicate effort.

**Comment by ljharb** [comment]
It'd be good to cut a major release before merging this new option, imo.
