### ISSUE TITLE
Use chalk to underline urls

### ISSUE THREAD

**Issue by jfmengels** [sarbbottam/eslint-find-rules#178]
We now output urls in verbose mode, but it's not necessarily always very clear that they are urls (it's a big blob of text at first glance, especially when the terminal is not very big)

![image](https://cloud.githubusercontent.com/assets/3869412/18780194/a12b6b8c-817c-11e6-896d-10c316087f02.png)

I just discovered Zeit's now, which outputs urls this way:
![image](https://cloud.githubusercontent.com/assets/3869412/18780004/c40af36c-817b-11e6-9a96-cbb91683e26d.png)
(it's even clearer when I hover the url in my terminal, but don't know how to make a screenshot of that on my computer)

and I found that [this](https://github.com/zeit/now/blob/545f644a4c9dbc519757e153469be5c317542523/bin/now-alias#L129) is the way it does that, using [chalk](https://www.npmjs.com/package/chalk).

I don't know what you think, but this looks to me like a nice addition to the tool :)

**Comment by ta2edchimp** [comment]
Definitely! I want coloured output since ... ever 😜
(Especially for the verbose diff output, to more easily distinguish unset from different configurations.)
