### ISSUE TITLE
fix semantic release

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-find-rules#198]
semantic release is broken for past few releases.

https://travis-ci.org/sarbbottam/eslint-find-rules/jobs/171707833#L355

```
 The commit the last release of this package was derived from is not in the direct history of the "master" branch.
```

**Comment by sarbbottam** [comment]
Semantic release seems to be back on track
https://travis-ci.org/sarbbottam/eslint-find-rules/jobs/171710493#L355

```
 ENOCHANGE There are no relevant changes, so no new version is released.
```

**Comment by sarbbottam** [comment]
Will keep the ticket open till a successful release.

**Comment by sarbbottam** [comment]
I guess I know, what has been the problem.
I forced pushed to one of the `PR` branches, with generic command `git ps -f`.
Which force pushed all the branches including the master, rewriting the history and bothered semantic release.

Lesson learnt the hard way. Now I have made the master branch protected. I can not accept pushes other than PR merge. Hopefully, that would prevent any unwanted mistakes.

**Comment by ljharb** [comment]
A better approach is being on the latest git, and having this in your `~/.gitconfig`:
```yaml
[push]
    default = current
```

**Comment by sarbbottam** [comment]
Updated. Thanks @ljharb, learnt quite a few things.

**Comment by sarbbottam** [comment]
Fixed - https://travis-ci.org/sarbbottam/eslint-find-rules/jobs/171897380#L353
