### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-find-rules#20]
I would be better to release this package asap, if we consider its current state is good enough for [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product)

Then we have to put a deprecation notice to [eslint-find-new-rules](https://github.com/kentcdodds/eslint-find-new-rules) and point it to this one.

Other wise we may end up addressing the same issues, in both the repo.

**Comment by ta2edchimp** [comment]
Yes, absolutely! I'd say, re-enable travis for this (renamed) repo and if all checks from #19 succeed, we'd pull the trigger.

I'll be more productive again too tomorrow ...
