### ISSUE TITLE
auto-merge and semantic release

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-find-rules#202]
>@sarbbottam: Please don't approve it via GitHub means, otherwise, the PR will get merged

>@ljharb: @sarbbottam i'd strongly caution against automerging on PR approval; i don't even think semantic-release is a safe idea.

>@sarbbottam:@ljharb I guess I was wrong about auto-merging. It is not enabled. I had to merge #199 by myself.

>>I'd strongly caution against auto-merging on PR approval; 

>Agreed

>>semantic-release

>Yea, it could be problematic sometimes, but has its benefits too. I am a bit biased but would be OK to let it go, if we all think so.

>@ta2edchimp: So, is it safe to approve the requested changes? (I never worked with the review feature before ...)

>>Re: auto merge on review approval

>Can we assure this is not activated?

>>Re: semantic release

>Besides "spamming" with updates when lots of PRs would get merged within a short period of time, I see no problem in having automatic releases for this tool. But this is something we should discuss / evaluate in a separate issue.

**Comment by sarbbottam** [comment]
<img width="783" alt="auto-merge" src="https://cloud.githubusercontent.com/assets/949380/19862202/9ddcb16e-9f4c-11e6-953b-a15a34604353.png">

This is why I stated, "Please don't approve it via GitHub means, otherwise, the PR will get merged".

But looks like GitHub will not automatically merge the PR. I would raise a simple PR with README updates, as a follow up and see how it behaves.

**Comment by sarbbottam** [comment]
>Besides "spamming" with updates when lots of PRs would get merged within a short period of time

My 💵 0.02.
Not sure if I would call it "spamming". `semantic-release` will not perform any release if it does not find the word "fix" or "feat" in the commit message. So we can control the release. Having said so, at times there could be multiple fixes/features across PRs, at that time it would release multiple version. In a way that's not bad, I suppose.

**Comment by ta2edchimp** [comment]
**Re: semantic release**

Yeah, that's why I put it in quotation marks; because on the one hand I see how it _semantically_ makes perfect sense to have a version released for each and every merged `fix` and `feat`, but on the other hand may _feel_ (to some) as if it would add a lot of noise to the release history.

To sum it up:
I see that there's the need to have more control over what gets released when, in what order and together with what other features and fixes in large projects, like ESLint for example (although I'm expecting them to also make use of an automated release workflow, I guess no one's `npm publish`ing every version manually from his machine).
But I think that semantically releasing new versions as we do it for this project (and other projects of its size) on merging into master with successfully running tests, is perfectly fine. 👌

**Comment by ljharb** [comment]
My concern about semantic-release is that it puts too much trust in PR authors/mergers. I definitely think each PR should explicitly state the semver level that applies to it - but the actual publisher should manually audit *every line of code* that is going into the publish. PRs can be reverted, but npm versions can't be unpublished (after 24 hours or a dep).

Manually creating and tagging a release takes me 5-10 minutes on all of my published projects (50-100). The tradeoff for that time is that I avoid the situation where someone clicks "merge" - something that doesn't require manual command line verification or testing - and all of a sudden people's builds are broken.

`semantic-release` prioritizes developer time over consumer time, and I think that is always a hostile decision. Things SHOULD take more time for the publisher/developer, if it means that the consumer is less likely to break.

**Comment by sarbbottam** [comment]
Maybe we can use https://github.com/conventional-changelog/standard-version to make manual release less tedious.

**Comment by ta2edchimp** [comment]
@sarbbottam Looks like a good alternative.

@ljharb Well, thanks for the reasonable explanation!
How do you usually manage responsibilities to publish new versions?

**Comment by ljharb** [comment]
@ta2edchimp usually I make a checklist, which includes waiting for travis to pass on the pushed tag before trying to publish; and then sometimes i might mandate a 👍 on the tagged commit from another collab before being able to publish. whatever works for the team.

**Comment by sarbbottam** [comment]
So we are good to get rid of `semantic-release`?

**Comment by ta2edchimp** [comment]
Looks good to me.

One last question: How do we determine *who* releases a new version? Simply let @sarbbottam do it generally and decide otherwise (e.g. within the context of a PR), should he be unavailable / absent (idk, on vacation or sth.) for some time?

**Comment by ljharb** [comment]
That seems fine. Typically the users who have publish rights are fewer than those who have commit rights anyways.

**Comment by ta2edchimp** [comment]
Sure, but those few (I guess it's the three of us? have to check) should somehow at least have agreed on a common scenario (e.g. "main publisher") and how to generally react when that will not work ... like, avoid having two users trying to publish a bugfix version at the same time (although I have to admit this will probably be a very rare scenario)... but maybe I'm just overcomplicating here. Let's just try it.

**Comment by sarbbottam** [comment]
@ta2edchimp you already have the publish rights. I added @ljharb too.

I will raise a PR to take out `semantic-release` and add  [standard-version](https://github.com/conventional-changelog/standard-version) to the workflow (needs to be manually executed).

Closing this ticket as we are good on the discussed approach. Please feel free to open the ticket should we need any further discussion.

**Comment by ta2edchimp** [comment]
I'm a bit confused: We closed this ticket, but the automatic release using `semantic-release` still is invoked on Travis, it just errors out upon execution (see [here](https://travis-ci.org/sarbbottam/eslint-find-rules/jobs/229185923#L1251)).
