### ISSUE TITLE
Bug: npm script erroneous

### ISSUE THREAD

**Issue by ta2edchimp** [sarbbottam/eslint-find-rules#22]
In [`package.json`](https://github.com/sarbbottam/eslint-find-rules/blob/master/package.json#L10) we have:

```JSON
"scripts": {
    "check-kentcdodds": "./bin.js eslint-config-kentcdodds"
  }
```

but running it will fail, due to

- `./bin.js` not existing,
- `eslint-config-kentcdodds` [not being successfully resolved](https://github.com/sarbbottam/eslint-find-rules/blob/master/src/rule-finder.js#L13).

@sarbbottam do we need this npm script?

**Comment by sarbbottam** [comment]
Nope!
