### ISSUE TITLE
v3 shows duplicate results for unused (-u)

### ISSUE THREAD

**Issue by alexilyaev** [sarbbottam/eslint-find-rules#281]
Just upgraded to v3, seeing duplicate results when running:  
`eslint-find-rules -u .eslintrc -n`

```
babel/new-cap               babel/new-cap               babel/no-invalid-this
babel/no-invalid-this       babel/object-curly-spacing  babel/object-curly-spacing
babel/semi                  babel/semi
```

You can check it out here:  
https://github.com/alexilyaev/react-es6-starter

**Comment by ta2edchimp** [comment]
First of all, thanks for providing that repo as a test case!

Strange thing is: [the `getRules` method exposed by ESLint](https://github.com/sarbbottam/eslint-find-rules/blob/master/src/lib/rule-finder.js#L74) includes rules of plugins on ESLint `^3.12`<sup>1)</sup>, but does not on ESLint `^4.0`. [So we duplicate the plugins' rules on ESLint `^3.12` when concatenating only `pluginsRules` and (what we think are only) `coreRules`](https://github.com/sarbbottam/eslint-find-rules/blob/master/src/lib/rule-finder.js#L90).  

This means, we **have** to get rid of the plugins' rules erroneously (?) included in the `getRules` methods response, when running using ESLint `^3.12`.

We could exclude every item from `coreRules` that matches `^[^\/]+\/` (starting at least one character not being a slash, followed by a slash) or that is included in `pluginRules` (using our `array-diff` utility function).  
Additionally we could do this only when `require('eslint').linter.version` matches `^3.12` according to semver, which I would definitely prefer.

---

1) This only happens within the context of `eslint-find-rules`. When only running the Node repl, requireing ESLint and calling `getRules`, the plugins' rules are not included.  
Like this  
`console.log(Array.from(require('eslint').linter.getRules().keys()).join('\n'));`

**Comment by ljharb** [comment]
Seems like just deduping unconditionally makes the most sense?

**Comment by ljharb** [comment]
I.e. `[...new Set(arr)]`
