### ISSUE TITLE
Add support to filter rules by ESLint rule meta category

### ISSUE THREAD

**Issue by ntwb** [sarbbottam/eslint-find-rules#283]
For example, the ESLint `getter-return` rule shipped in ESLint 4.2

This rule is ***not*** included in the ESLint `recommended` config but ***is*** listed in the `Possible Errors` category: https://github.com/eslint/eslint/blob/master/lib/rules/getter-return.js#L49

Currently if I run `eslint-find-rules --unused --no-error` on my _shared config_ this returns ~40 rules that I don't use and have no plans on using.

It'd be great if I could do `eslint-find-rules --unused --no-error --category possible-errors`, that would make it super easy to run after updating ESLint to determine if any ***new*** `Possible Errors` rules have shipped in ESLint.

**Comment by ljharb** [comment]
Those categories are pretty arbitrary; there's plenty of things outside "possible errors" that are possible errors, including things in the es6 category.
