### ISSUE TITLE
Exit status

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-find-rules#31]
Currently exit status is 0, the original module used process.exit(1), I removed that on purpose, I did not want the error to scroll past the viewport.

Should there be an option `--exit=1` default to `0`?
May be in [CI environment](https://github.com/watson/is-ci) `exit` status is 1?

Thoughts?

**Comment by sarbbottam** [comment]
> I did not want the error to scroll past the viewport

Did not realize `-s` to silent the output.

**Comment by ta2edchimp** [comment]
I think it's a good idea to be able to specify whether to exit with non-zero codes.

**Comment by sarbbottam** [comment]
What should be the default exit status? `0`?

**Comment by ta2edchimp** [comment]
Hmm... the more I think about it, the more I think that `1` should be default.
You usually want to have a comprehensive rule set, don't you?
When liberately omitting some rules, add `--no-error|-n`?
