### ISSUE TITLE
Doesn't find unused rules in @typescript-eslint/eslint-plugin

### ISSUE THREAD

**Issue by himynameisdave** [sarbbottam/eslint-find-rules#316]
I noticed that this [newly added rule](https://github.com/typescript-eslint/typescript-eslint/pull/1522) was added in [`@typescript-eslint/eslint-plugin`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin), and I realized that it was not being found by this tool. 😦 

Perhaps this is an issue with scanning monorepos?

**Comment by ljharb** [comment]
That rule requires v2.22.0, have you fully updated? This tool uses what’s installed locally.

**Comment by himynameisdave** [comment]
Thanks for the reply (and for contributing to this invaluable tool). 💯 👍 

Yep I updated it the plugin locally, then [ran my usual command](https://github.com/himynameisdave/eslint-config-himynameisdave/blob/master/package.json#L9) which I would expect to have found those new rules [added in v2.22.0](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/CHANGELOG.md#2220-2020-03-02). 

If you need, I can push the plugin package bumps and you can try for yourself in my config repo?

**Comment by ljharb** [comment]
Sure, a repro repo would be most helpful.

**Comment by himynameisdave** [comment]
After testing this more locally, I have realized that I had misconfigured something (was running it against a configuration which didn't use this plugin), my bad!

Thanks for the help! 👍
