### ISSUE TITLE
Handle typescript-eslint configuration

### ISSUE THREAD

**Issue by nicolashenry** [sarbbottam/eslint-find-rules#322]
When it runs in a project containing only "*.ts" files (so not any "*.js" file) this error occurs:
![image](https://user-images.githubusercontent.com/139160/81693858-d9cbba00-9460-11ea-9cfd-51c385c98ff2.png)

It seems that the issue come from this line : https://github.com/sarbbottam/eslint-find-rules/blob/ab323d6746ec9f60d24d0a26929e4ea01275d17a/src/lib/rule-finder.js#L84

It could be nice to have a way to configure the glob pattern or maybe just the extension part (see --ext option in eslint cli https://eslint.org/docs/user-guide/command-line-interface#options)

Thanks!

**Comment by ljharb** [comment]
We could add the ext option, sure, mirroring what eslint does.
