### ISSUE TITLE
git clone error on windows

### ISSUE THREAD

**Issue by nicolashenry** [sarbbottam/eslint-find-rules#323]
I wanted to clone this repository on windows to do some contribution but this error occurs:
```sh
$ git clone https://github.com/sarbbottam/eslint-find-rules.git
Cloning into 'eslint-find-rules'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
Receiving objects:  99% (1119/1130)d 1 (delta 0), pack-reused 1127
Receiving objects: 100% (1130/1130), 238.96 KiB | 650.00 KiB/s, done.
Resolving deltas: 100% (615/615), done.
error: invalid path 'test/fixtures/<v5/eslint-dedupe-plugin-rules.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
It seems that the "<" character is not supported in Windows file systems, could you rename the folder "test/fixtures/<v5" to something else?

Thanks!

**Comment by ljharb** [comment]
What happens if you clone it in git-bash or WSL?

**Comment by nicolashenry** [comment]
This is the result in git bash and I can't use WSL (I am still on Windows 7).

**Comment by ljharb** [comment]
Windows 7 went EOL in January :-/

**Comment by nicolashenry** [comment]
Say that to my employer :p but I am sure that it would be the same on Windows 10 with git bash anyway.

**Comment by nicolashenry** [comment]
From https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file the list of reserved character on windows:
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)

**Comment by ljharb** [comment]
lol, happy to :-p

so yes, a PR that renames that dir would be fine, altho it's unfortunate any time windows' filesystem flaws imposes a cost on the wider ecocystem.
