### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [sarbbottam/eslint-find-rules#330]
I just saw that `eslint-find-rules` is updated to `v3.6.0`, but I can't find any CHANGELOG to check out the changes.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work @sarbbottam & @ljharb! 🙂

**Comment by ljharb** [comment]
https://github.com/sarbbottam/eslint-find-rules/blob/master/CHANGELOG.md points to https://github.com/sarbbottam/eslint-find-rules/releases, but v3.5 and v3.6 don't have a release created yet.

I'll make one, but note if you click on each release (https://github.com/sarbbottam/eslint-find-rules/releases/tag/v3.5.0) you can click on "compare" and compare to the previous one (https://github.com/sarbbottam/eslint-find-rules/compare/v3.4.0...v3.5.0) which is what i'll be using anyways to make the release summary.

**Comment by ljharb** [comment]
Releases created.

**Comment by MichaelDeBoey** [comment]
Thanks @ljharb! 👊
