### ISSUE TITLE
Breaks with ESLint 7.8.0

### ISSUE THREAD

**Issue by soda0289** [sarbbottam/eslint-find-rules#331]
I get the following error with eslint 7.8.0:

Error: eslint naming functions not found

Looks like this tool tries to access the normalization functions from eslint in the file "eslint/lib/shared/naming".
https://github.com/sarbbottam/eslint-find-rules/blob/master/src/lib/normalize-plugin-name.js#L13

Looks like that file was removed in this change:
https://github.com/eslint/eslint/pull/13613/files#diff-bdb20110f0ab3020c5ffa945a4b79bce

**Comment by soda0289** [comment]
Those normalization functions have been moved to eslint/eslintrc package.
https://github.com/eslint/eslintrc/blob/main/lib/shared/naming.js

I can push fix to include this package as dependency and remove the require('eslint/....')

**Comment by ljharb** [comment]
A PR would be great; unfortunately this broke in a minor version.

**Comment by soda0289** [comment]
@ljharb Created PR #332

**Comment by soda0289** [comment]
Confirmed eslint 7.8.0 and 7.9.0 work with eslint-find-fules 3.6.1
