### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jimmywarting** [sarbbottam/eslint-find-rules#334]
Tried contributing but many test failed...

1. File an issue and discuss your proposed solution first
2. Fork and clone the repo
3. $ npm install to install dependencies
4. $ npm run validate to validate you've got it working

But it didn't validate

**Comment by ljharb** [comment]
In what node version?

**Comment by jimmywarting** [comment]
v16.5.0

**Comment by ljharb** [comment]
I'm indeed seeing a bunch of errors like `Error: Failed to load plugin 'plugin' declared in '--config': Cannot find module 'eslint-plugin-plugin'`.

**Comment by ljharb** [comment]
Seems like it broke in eslint v7.10; it passes in v7.9.

**Comment by ljharb** [comment]
Will be fixed by #335.
