### ISSUE TITLE
bump `cliui` to resolve `ansi-regex` ReDoS

### ISSUE THREAD

**Issue by csantos1113** [sarbbottam/eslint-find-rules#349]
Could it be possible to upgrade these dependencies to resolve ReDoS vulnerability?

- [`ansi-regex`](https://github.com/chalk/ansi-regex/releases) is used by [`strip-ansi`](https://github.com/chalk/strip-ansi/releases)
- `strip-ansi` is used by [`cliui`](https://github.com/yargs/cliui/releases)
- `cliui` is used by this package

**Comment by ljharb** [comment]
Why? Most ReDOS vulnerabilities are self-attacks, meaning, not a vulnerability.

**Comment by csantos1113** [comment]
I'm going to close this issue because the version of `ansi-regex` that is indirectly installed is safe
