### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by ljharb** [sarbbottam/eslint-find-rules#51]
I'd love to know what changes between versions without having to read the commit log :-)

**Comment by sarbbottam** [comment]
Change log is associated with the [corresponding releases](https://github.com/sarbbottam/eslint-find-rules/releases). 

Are you looking for something else?

**Comment by ljharb** [comment]
aha, thanks. I'd expect a `CHANGELOG.md` file in the root of the repo.

**Comment by kentcdodds** [comment]
Yeah, in Angular-formly, I have a CHANGELOG.MD that just explains this and links to releases. We could do this.

**Comment by sarbbottam** [comment]
Closed by https://github.com/sarbbottam/eslint-find-rules/pull/53
