### ISSUE TITLE
Feature: Compare / Diff two or more configs

### ISSUE THREAD

**Issue by ta2edchimp** [sarbbottam/eslint-find-rules#6]
Add an option to compare the rules configured by two (or even more?) ESLint configs.

**Comment by sarbbottam** [comment]
`--diff | -d` could be the option.

❓ 
* `eslint-rule-finder -d path/to/file-a path/to/file-b`
* must provide two files?
* how the output should look like?

**Comment by ta2edchimp** [comment]
>how the output should look like?

Thought of using `cli-table2` and printing the used configs like `JSON.stringify`. One rule per row.

**Comment by sarbbottam** [comment]
just came across [cliui](https://github.com/yargs/cliui), might be helpful.

**Comment by ta2edchimp** [comment]
Awesome! I fiddled around with that `cli-table2` today and it just did not do the job as I'd have liked it to (too much to be done for the desired result).

Nice finding!

**Comment by ta2edchimp** [comment]
I'd rather thought of showing the actual differences of the compared configs.
There's little value in a pure list, I'd have to dig deep into the configs to see where they **actually** differ.

I'm reopening this and reassigning this to myself.

If you guys think, that displaying the actual differences would be too verbose, please share your thoughts, we could hide it behind a corresponding `loglevel` option (re #7).

**Comment by sarbbottam** [comment]
@ta2edchimp doc you think we can close this issue?

**Comment by ta2edchimp** [comment]
Absolutely.
