### ISSUE TITLE
Feature: Verbose output

### ISSUE THREAD

**Issue by ta2edchimp** [sarbbottam/eslint-find-rules#7]
Add a `--verbose` option. When used, print for example when there's no rule unconfigured (atm. this has no output at all).

We could easily make use `npm-log` for this.

**Comment by ta2edchimp** [comment]
How should we assign the output to different log levels?
By default, [`npmlog`](https://www.npmjs.com/package/npmlog) (I spelled it wrong in the op) comes with these log levels:

- `silly`: I think this will be unused, but could eventually be used to simply log everything.
- `verbose`: Print things like "there's no rule unconfigured" (relates to [the original package's issue #24](https://github.com/kentcdodds/eslint-find-new-rules/issues/24).
- `info`: I think this one should become the default output level.
- ~~`http`~~: we do not make any http request, so it'll stay unused.
- `warn` & `error`: obviously as usual, when there's sth that went wrong.

Any other ideas? Did I miss anything?

**Comment by sarbbottam** [comment]
Sounds good!

Wondering if `silly` and `verbose` should be combined.

**Comment by ta2edchimp** [comment]
Yeah I think we can skip `silly` completely, but `verbose` is sth. I'd really like to have in.

**Comment by sarbbottam** [comment]
We might want to address #9 along with this.

**Comment by ta2edchimp** [comment]
Yep

**Comment by ta2edchimp** [comment]
Another thing that came into my mind, when making the tabular output / sorting the rules' names alphabetically:
We probably should also group those rules, like in a batch of rules for `eslint (default)` and all loaded plugins `eslint-plugin-import` etc. ...

**Comment by sarbbottam** [comment]
Go for it.

**Comment by sarbbottam** [comment]
@ta2edchimp do you think we can close this issue?

**Comment by ta2edchimp** [comment]
Yep.
