### ISSUE TITLE
`eslint` dependency

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-find-rules#70]
Instead of hard code `eslint` directory, use [require.resolve](https://nodejs.org/api/globals.html#globals_require_resolve) to detect it.

If no `eslint` is found in the `PATH` display proper error.

Refer #69

**Comment by sarbbottam** [comment]
@ta2edchimp, @kentcdodds could you take a look?

**Comment by kentcdodds** [comment]
I probably won't have time honestly

**Comment by sarbbottam** [comment]
no worries!!

**Comment by sarbbottam** [comment]
oops commented in the issue instead of PR., deleting the comments as they are not relevant.
