### ISSUE TITLE
Breaking change in minor version

### ISSUE THREAD

**Issue by ljharb** [sarbbottam/eslint-find-rules#83]
So, first, https://github.com/sarbbottam/eslint-find-rules/commit/93a68b662d97581542cbcc49370a290088ce8b13 is a breaking change, and should not have been released as a minor version.

Second, it is failing for me when run as a local utility. Using `npm run-script`s, `eslint-find-rules` can be invoked directly, since `npm` puts it in the PATH - so your method of determining "is global" is flawed.

**Comment by ljharb** [comment]
ping @sarbbottam @kentcdodds

**Comment by sarbbottam** [comment]
@ljharb extremely sorry about it. We use `semantic-release`, which looks for `BREAKING CHANGE` in the commit message to release a major version. Making a re-release reverting this change.

**Comment by ljharb** [comment]
Thanks!
