### ISSUE TITLE
eslint-find-rules being used as a global utility?

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-find-rules#85]
[is-global.js](https://github.com/sarbbottam/eslint-find-rules/blob/master/src/bin/is-global.js) fails in node 4.4

- https://travis-ci.org/ljharb/eslint-config/jobs/128434647#L499
- https://travis-ci.org/ljharb/eslint-config/jobs/128433311#L491

Utilization is commented now, refer #83 
Does it even make sense to keep it or just update the README, that this must not be used as a global utility.

@ta2edchimp @kentcdodds  thoughts.

**Comment by kentcdodds** [comment]
Yeah, just document that people should use it as a local utility. People can do what they want ¯\\\_(ツ)_/¯
