### ISSUE TITLE
Feature: better output

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-find-rules#9]
Current output looks a bit clumsy, can we make it better?

**Comment by ta2edchimp** [comment]
Could be a lot, but why not one rule per line, link to description on eslint.org, if available?

**Comment by sarbbottam** [comment]
>why not one rule per line

I tried that initially but it scrolls past the window. I was expecting to display it in similar to `ls` command at least.

**Comment by ta2edchimp** [comment]
Good idea. We could use `cli-table2` (or sth. like that) with a dynamic column width but without borders.
I used it with my `what-the-status-code-cli` implementation and I like it!

**Comment by sarbbottam** [comment]
just came across [cliui](https://github.com/yargs/cliui), might be helpful.
